name: geo_flutter_exam
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '3.0.5'

dependencies:
  flutter:
    sdk: flutter
  latlong2: ^0.8.1
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.6
  flutter_polyline_points: ^1.0.0
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
